src/HTBox.Web/Controllers/UserRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HTBox.Web.Models;
using Newtonsoft.Json;
using System.Collections;
using System.Transactions;

namespace HTBox.Web.Controllers
{
    public class UserRoleController : Controller
    {
        private WebPagesContext db = new WebPagesContext();
        //
        // GET: /UserRole/

        public ActionResult Index()
        {
            
            return View();

        }

        public ActionResult GetData(string id = null)//此参数名需要与 tree setting 属性 相同
        {
            IEnumerable<Webpages_Roles> allRoles;
            if (id == null)
                allRoles = db.WebPagesRoles.Where(o => o.Deep == 0);
            else
                allRoles = db.WebPagesRoles.Find(id).GetOneFloorGroups(db);
            List<ZTree> list = new List<ZTree>();
            if (allRoles.Count() == 0)
            {
                var root = Webpages_Roles.GetOrCreateRoot();
                list.Add(new ZTree(root));
            }
            else
            {
                Func<IEnumerable<Webpages_Roles>, string, bool> f = null;

                f = (n, parent) =>
                    {
                        foreach (var r in n)
                        {
                            var z = new ZTree(r);
                            z.ParentId = parent;
                            list.Add(z);
                            foreach (var user in r.GetUsers(false))
                            {
                                var u = new ZTree(user);
                                u.ParentId = r.Code;
                                list.Add(u);
                            }
                            f(r.GetOneFloorGroups(), r.Code);

                        }
                        return true;
                    };
                f(allRoles, null);
            }
            return Content(JsonConvert.SerializeObject(list), "application/json");
        }

        public ActionResult EditUser(int userid)
        {
            var user = db.UserProfiles.Find(userid);
            if (user == null)
                return HttpNotFound();
            return PartialView(user);
        }
        public ActionResult CreateUser(string code)
        {
            ViewBag.RoleCode = code;
            Webpages_UserProfile user=new Webpages_UserProfile()
            {
                IndexOrder = 1
            };
            return View(user);
        }
        [HttpPost]
        public ActionResult CreateUser(Webpages_UserProfile user, string roleCode)
        {
            using (TransactionScope ts = new TransactionScope())
            {
                if (db.UserProfiles.Where(o => o.UserName == user.UserName).Any())
                {
                    return Content("User Exist");
                }
                db.UserProfiles.Add(user);
                db.SaveChanges();
                Webpages_UsersInRoles userRole = new Webpages_UsersInRoles()
                {
                    RoleCode = roleCode,
                    UserId = user.UserId
                };
                db.WebPagesUsersInRoles.Add(userRole);
                db.SaveChanges();
                ts.Complete();
                return Content(Boolean.TrueString);
            }
        }
        [HttpPost]
        public ActionResult EditUser(Webpages_UserProfile user)
        {
            if (ModelState.IsValid)
            {
                if (db.UserProfiles.Where(o => o.UserName == user.UserName && o.UserId != user.UserId).Any())
                {
                    return Content("User Exist");
                }
                db.Entry(user).State = System.Data.EntityState.Modified;
                db.SaveChanges();
            }
            return Content(Boolean.TrueString);
        }
        public ActionResult CreateRole(string parentNodeCode = null)
        {
            if (!string.IsNullOrEmpty(parentNodeCode))
            {
                var parent = db.WebPagesRoles.Find(parentNodeCode);
                if (parent == null)
                    return HttpNotFound();
                ViewBag.ParentCode = parent.Code;
                ViewBag.ParentName = parent.RoleName;
            }
            Webpages_Roles role = new Webpages_Roles()
            {
                IndexOrder = 1
            };
            return View(role);
        }
        [HttpPost]
        public ActionResult CreateRole(Webpages_Roles role, string parentNodeCode = null)
        {
            if (!string.IsNullOrEmpty(parentNodeCode))
            {
                
                var parent = db.WebPagesRoles.Find(parentNodeCode);
                if (parent == null)
                {
                    return HttpNotFound();
                }
                if (parent.GetSubRoleByName(role.RoleName, db) != null)
                {
                    return Content(role.RoleName + " Exist!");
                }
                //生成新的编码
                string codeHead = parent.Code + "-";
                var curLevelCodes = (from r in db.WebPagesRoles
                                     where r.Code.IndexOf(codeHead) == 0
                                     orderby r.Code
                                     select r.Code).ToList();

                if (curLevelCodes.Count == 0)
                {
                    role.Code = codeHead + "1";
                }
                else
                {
                    //只申请这么多个(groups.Length)标志位足够了,
                    //因为,如果全占了,就返回groups.Length+1,
                    //如果没有全占,那么中间肯定有空位
                    System.Collections.BitArray ba = new BitArray(curLevelCodes.Count);
                    //找空号
                    int ValidID = -1;
                    foreach (var c in curLevelCodes)
                    {
                        string[] ary = c.Split('-');
                        int tmp = Convert.ToInt32(ary[ary.Length - 1]);
                        if (tmp > curLevelCodes.Count)//超出的不予理会
                            continue;
                        ba[tmp - 1] = true;//打标
                    }
                    for (int i = 0; i < ba.Length; i++)
                    {//从中查找空位
                        if (!ba[i])
                        {
                            ValidID = i + 1;
                            break;
                        }

                    }
                    if (ValidID == -1)//位全占
                        ValidID = curLevelCodes.Count + 1;
                    role.Code = codeHead + ValidID;
                }
            }
            else
            {
                role.Code = role.Type.ToString();
            }
            var tmpAry = role.Code.Split('-');
            role.Type = Convert.ToInt32(tmpAry[0]);
            role.Deep = tmpAry.Length - 1;
            db.WebPagesRoles.Add(role);
            db.SaveChanges();
            return Content(Boolean.TrueString);
        }
        public ActionResult EditRole(string roleCode)
        {
            var role = db.WebPagesRoles.Find(roleCode);
            if (role == null)
                return HttpNotFound();
            return PartialView(role);
        }

        [HttpPost]
        public ActionResult EditRole(Webpages_Roles role)
        {
            if (ModelState.IsValid)
            {
                db.Entry(role).State = System.Data.EntityState.Modified;
                db.SaveChanges();
            }
            return Content(Boolean.TrueString);
        }

        public ActionResult DeleteUser(int userid)
        {
            using (TransactionScope ts = new TransactionScope())
            {
                var menu = db.UserProfiles.Find(userid);
                db.Entry(menu).State = System.Data.EntityState.Deleted;
                foreach (var vuser in db.Webpages_VUsers.Where(o => o.UserID == userid).ToList())
                {
                    foreach (var tree in db.MenuTreeRights.Where(o => o.VuserID == vuser.VUserId).ToList())
                    {
                        db.Entry(tree).State = System.Data.EntityState.Deleted;
                    }
                    db.Entry(vuser).State = System.Data.EntityState.Deleted;

                }
                foreach (var vuser in db.WebPagesUsersInRoles.Where(o => o.UserId == userid).ToList())
                {
                    db.Entry(vuser).State = System.Data.EntityState.Deleted;
                }
                db.SaveChanges();
                ts.Complete();
                return Content(Boolean.TrueString);
            }

        }

        public ActionResult DeleteRole(string roleCode)
        {
            using (TransactionScope ts = new TransactionScope())
            {
                var menu = db.WebPagesRoles.Find(roleCode);
                db.Entry(menu).State = System.Data.EntityState.Deleted;
                foreach (var vuser in db.Webpages_VUsers.Where(o => o.RoleID == roleCode))
                {
                    foreach (var tree in db.MenuTreeRights.Where(o => o.VuserID == vuser.VUserId))
                    {
                        db.Entry(tree).State = System.Data.EntityState.Deleted;
                    }
                    db.Entry(vuser).State = System.Data.EntityState.Deleted;

                }
                foreach (var vuser in db.WebPagesUsersInRoles.Where(o => o.RoleCode == roleCode))
                {
                    db.Entry(vuser).State = System.Data.EntityState.Deleted;
                }
                db.SaveChanges();
                ts.Complete();
                return Content(Boolean.TrueString);
            }

        }
    }
}

src/HTBox.Web/Views/UserRole/CreateRole.cshtml
@model HTBox.Web.Models.Webpages_Roles
@{
    Layout = null;
}
@using (Ajax.BeginForm("CreateRole", "UserRole", null,
    new AjaxOptions
    {
        UpdateTargetId = "update-message",
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        OnSuccess = "addSuccess",

    },
    new { @id = "updateUserForm" }))
{
    @Html.ValidationSummary(true)
    <div id="update-message" class="error invisible"></div>
    <fieldset>

        <legend>Webpages_Roles</legend>
          
          @Html.Hidden("parentNodeCode", (string)ViewBag.ParentCode)
         <div class="editor-label">
            @Html.Label("Parent", "Parent")
        </div>
        <div class="editor-field">
            @Html.Label("Parent", (string)ViewBag.ParentName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RoleName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RoleName)
            @Html.ValidationMessageFor(model => model.RoleName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IndexOrder)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IndexOrder)
            @Html.ValidationMessageFor(model => model.IndexOrder)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Master)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Master)
            @Html.ValidationMessageFor(model => model.Master)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Expression)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Expression)
            @Html.ValidationMessageFor(model => model.Expression)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Remark)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Remark)
            @Html.ValidationMessageFor(model => model.Remark)
        </div>
        <p>
        <input type="submit" value="Save" />
        </p>
    </fieldset>
}

src/HTBox.Web/Views/UserRole/CreateUser.cshtml
@model HTBox.Web.Models.Webpages_UserProfile
@{
    Layout = null;
}
@using (Ajax.BeginForm("CreateUser", "UserRole", null,
    new AjaxOptions
    {
        UpdateTargetId = "update-message",
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        OnSuccess = "addSuccess",
        
    },
    new { @id = "updateUserForm" }))
{
      @Html.ValidationSummary(true)
     <div id="update-message" class="error invisible"></div>
    <fieldset>
        <legend>Webpages_UserProfile</legend>
        @Html.HiddenFor(model => model.UserId)
            @Html.Hidden("roleCode", (string)ViewBag.RoleCode)
        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IndexOrder)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IndexOrder)
            @Html.ValidationMessageFor(model => model.IndexOrder)
        </div>
         <p>
        <input type="submit" value="Save" />
        </p>
    </fieldset>
}

src/HTBox.Web/Views/UserRole/DeleteRole.cshtml
@{
    Layout = null;
}

src/HTBox.Web/Views/UserRole/DeleteUser.cshtml
@{
    Layout = null;
}

src/HTBox.Web/Views/UserRole/EditRole.cshtml
@model HTBox.Web.Models.Webpages_Roles
@{
    Layout = null;
}
@using (Ajax.BeginForm("EditRole", "UserRole", null,
    new AjaxOptions
    {
        UpdateTargetId = "update-message",
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        OnSuccess = "updateSuccess",

    },
    new { @id = "updateUserForm" }))
{
    @Html.ValidationSummary(true)
    <div id="update-message" class="error invisible"></div>
    <fieldset>
        <legend>Webpages_Roles</legend>

         <div class="editor-label">
            @Html.LabelFor(model => model.Code)
        </div>
        <div class="editor-field">
            @Html.DisplayTextFor(model => model.Code)
            @Html.HiddenFor(model => model.Code)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RoleName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RoleName)
            @Html.ValidationMessageFor(model => model.RoleName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IndexOrder)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IndexOrder)
            @Html.ValidationMessageFor(model => model.IndexOrder)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Master)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Master)
            @Html.ValidationMessageFor(model => model.Master)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Expression)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Expression)
            @Html.ValidationMessageFor(model => model.Expression)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Remark)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Remark)
            @Html.ValidationMessageFor(model => model.Remark)
        </div>
          <p>
        <input type="submit" value="Save" />
        </p>
    </fieldset>
}

src/HTBox.Web/Views/UserRole/EditUser.cshtml
@model HTBox.Web.Models.Webpages_UserProfile
@{
    Layout = null;
}
@using (Ajax.BeginForm("EditUser", "UserRole", null,
    new AjaxOptions
    {
        UpdateTargetId = "update-message",
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        OnSuccess = "updateSuccess",
        
    },
    new { @id = "updateUserForm" }))
{
    @Html.ValidationSummary(true)
     <div id="update-message" class="error invisible"></div>
    <fieldset>
        <legend>Webpages_UserProfile</legend>
        @Html.HiddenFor(model => model.UserId)
        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.IndexOrder)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IndexOrder)
            @Html.ValidationMessageFor(model => model.IndexOrder)
        </div>
         <p>
        <input type="submit" value="Save" />
        </p>
    </fieldset>
}

src/HTBox.Web/Views/UserRole/GetData.cshtml
@{
    Layout = null;
}

src/HTBox.Web/Views/UserRole/index.cshtml
@{
    ViewBag.Title = "index";
}
@Styles.Render("~/Content/ztree")
@Scripts.Render("~/bundles/ztree")
@Scripts.Render("~/bundles/jqueryui")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/menu")
<h2>
    User And Role   </h2>
<script type="text/javascript">
		<!--
    var setting = {
        async: {
            enable: true,
            url: '@Url.Action("GetData", "UserRole")',
            autoParam: ["id", "name=n"]
        },
        view: {
            addHoverDom: addHoverDom,
            removeHoverDom: removeHoverDom,
            selectedMulti: false
        },
        edit: {
            enable: true,
            editNameSelectAll: true,
            showRemoveBtn: showRemoveBtn,
            showRenameBtn: showRenameBtn
        },
        data: {
            simpleData: {
                enable: true
            }
        },
     
        callback: {
            beforeDrag: beforeDrag,
            beforeEditName: beforeEditName,
            beforeRemove: beforeRemove,
            onRemove: onRemove,
            onClick: this.onClick
        }
    };


    var log, className = "dark";
    function beforeDrag(treeId, treeNodes) {
        return false;
    }
    function beforeEditName(treeId, treeNode) {
        className = (className === "dark" ? "" : "dark");

        var zTree = $.fn.zTree.getZTreeObj("treeDemo");
        zTree.selectNode(treeNode);
        return confirm("Start node '" + treeNode.name + "' editorial status?");
    }
    function beforeRemove(treeId, treeNode) {
        className = (className === "dark" ? "" : "dark");

        var zTree = $.fn.zTree.getZTreeObj("treeDemo");
        zTree.selectNode(treeNode);
        return confirm("Confirm delete node '" + treeNode.name + "'?");
    }
    function onRemove(e, treeId, treeNode) {
        var url;
        if (treeNode.nodeType == "User")
            url = '@Url.Action("DeleteUser", "UserRole")?userid=' + treeNode.id;
        else
            url = '@Url.Action("DeleteRole", "UserRole")?roleCode=' + treeNode.id;
        $.get(url, function (data) {
            if (data != "True") {
                $("#update-message").html(data);
            }
        }).error(function (er) {
            var dialogDiv = $('#updateDialog');
            dialogDiv.html(er.responseText);
       
        });
    }

    function showRemoveBtn(treeId, treeNode) {
        return !( treeNode.children);
    }
    function showRenameBtn(treeId, treeNode) {
        return false;
    }
    var clickedNode;
    function onClick(e, treeId, node) {
        clickedNode = node;
        var url;
        if (node.nodeType == "User")
            url = '@Url.Action("EditUser", "UserRole")?userid=' + node.id;
        else
            url = '@Url.Action("EditRole", "UserRole")?roleCode=' + node.id;
        var dialogDiv = $('#updateDialog');
        $.get(url, function (data) {
            dialogDiv.html(data);
            //validation
            var $form = $("#updateUserForm");
            // Unbind existing validation
            $form.unbind();
            $form.data("validator", null);
         
        });
    }


    var newCount = 1;
    function addHoverDom(treeId, treeNode) {
        var sObj = $("#" + treeNode.tId + "_span");
        if (treeNode.editNameFlag || $("#addBtn_" + treeNode.tId).length > 0) return;

        if (treeNode.nodeType != 'User') {
            var addUserStr = "<span class='button addUser' id='addUserBtn_" + treeNode.tId
				+ "' title='add User' onfocus='this.blur();'></span>";
            sObj.after(addUserStr);
            var userbtn = $("#addUserBtn_" + treeNode.tId);
            if (userbtn) userbtn.bind("click", function () {
                clickedNode = treeNode;
                url = '@Url.Action("CreateUser", "UserRole")?code=' + treeNode.id;
                var dialogDiv = $('#updateDialog');
                $.get(url, function (data) {
                    dialogDiv.html(data);
                    //validation
                    var $form = $("#updateUserForm");
                    // Unbind existing validation
                    $form.unbind();
                    $form.data("validator", null);
                });
                return false;
            });

            var addRoleStr = "<span class='button add' id='addBtn_" + treeNode.tId
				+ "' title='add Role' onfocus='this.blur();'></span>";
            sObj.after(addRoleStr);
            var btn = $("#addBtn_" + treeNode.tId);
            if (btn) btn.bind("click", function () {
                clickedNode = treeNode;
                url = '@Url.Action("CreateRole", "UserRole")?parentNodeCode=' + treeNode.id;
                var dialogDiv = $('#updateDialog');
                $.get(url, function (data) {
                    dialogDiv.html(data);
                    //validation
                    var $form = $("#updateUserForm");
                    // Unbind existing validation
                    $form.unbind();
                    $form.data("validator", null);
                });

                return false;
            });
        }
    };
    function removeHoverDom(treeId, treeNode) {
        $("#addBtn_" + treeNode.tId).unbind().remove();
        $("#addUserBtn_" + treeNode.tId).unbind().remove();
    };
    function selectAll() {
        var zTree = $.fn.zTree.getZTreeObj("treeDemo");
        zTree.setting.edit.editNameSelectAll = $("#selectAll").attr("checked");
    }

    $(document).ready(function () {
        $.fn.zTree.init($("#treeDemo"), setting);
        $("#selectAll").bind("click", selectAll);
    });

    function updateSuccess() {
        if ($("#update-message").html() == "True") {
            //we update the table's info

            var zTree = $.fn.zTree.getZTreeObj("treeDemo");
            zTree.editName(clickedNode);
            if (clickedNode.nodeType == "User")
                zTree.cancelEditName($("#UserName").val()); //newname
            else
                zTree.cancelEditName($("#RoleName").val()); //newname

            //$('#updateDialog').dialog('close');
            $("#update-message").html("");

        }
        else {
            $("#update-message").show();
        }
    }
    function addSuccess() {
        if ($("#update-message").html() == "True") {
            //we update the table's info

            var zTree = $.fn.zTree.getZTreeObj("treeDemo");

            zTree.reAsyncChildNodes(clickedNode, "refresh", false);

            //$('#updateDialog').dialog('close');
            $("#update-message").html("");

        }
        else {
            $("#update-message").show();
        }
    }

</script>
<div style="display: inline;">
    <div>@Html.ActionLink("Reload","") </div>
    <div style="display: inline-block; width: 300px; vertical-align: top;">
        <ul id="treeDemo" class="ztree">
        </ul>
    </div>
    <div id="updateDialog" style="display: inline-block">
    </div>
</div>